# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source definitions common for different shells
if [ -f ~/.commonrc ]; then
	. ~/.commonrc
fi

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k" # set by `omz`


# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  dotenv
  poetry
  virtualenv
  z
)

source "$ZSH/oh-my-zsh.sh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# git
alias grtt='cd "$(git rev-parse --show-superproject-working-tree || echo .)"'

# macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
    # meld
    PATH="$PATH:/Applications/p4merge.app/Contents/MacOS:/Applications/kdiff3.app/Contents/MacOS/:/Applications/DiffMerge.app/Contents/MacOS/:/Applications/Meld.app/Contents/MacOS/"
    ulimit -S -n 2048

    # iTerm2 shell integration
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

fi


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ctr-t for fzf
export FZF_CTRL_T_OPTS=" \
  --preview 'if [ -d "{}" ]; then tree -C {}; else; bat -n --color=always {};fi' \
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# alt-c for fzf
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"


export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# https://github.com/AdoptOpenJDK/homebrew-openjdk
jdk() {
        version=$1
        export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
        java -version
 }

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm


if command -v direnv &> /dev/null
then
	eval "$(direnv hook zsh)"
fi


# MidnightCommander
alias mc='source /usr/lib/mc/mc-wrapper.sh'


[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Created by `pipx` on 2024-10-14 11:57:40
export PATH="$PATH:/home/lukas/.local/bin"

# nix
export PATH=$PATH:/nix/var/nix/profiles/default/bin/

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Created by `pipx` on 2025-01-17 07:03:08
    export PATH="$PATH:/Users/lukaswoodtli/.local/bin"
fi

# Gardena
alias poe='poetry run poe'
#alias bnw='~/.cache/pypoetry/virtualenvs/bnwcli-mkecf-Tn-py3.12/bin/python3 ~/.cache/pypoetry/virtualenvs/bnwcli-mkecf-Tn-py3.12/bin/bnw'
# lb_sniffer Wireshark
export PATH=${HOME}/.local/opt/wireshark-git/bin:$PATH

# Zephyr west
source ~/.dotfiles/zsh/_west

# GW ID's
export MY_HCGW_ID='0fa20327-8353-448d-a73c-d868f1cf8a7c'

# Jetbrains tools
function pycharm() { /home/lukas/.local/bin/pycharm $@ &> /dev/null & }
function clion() { /home/lukas/.local/bin/clion $@ &> /dev/null & }
function rustrover() { /home/lukas/.local/bin/rustrover $@ &> /dev/null & }
function idea() { /home/lukas/.local/bin/idea $@ &> /dev/null & }

# Workaround Kubuntu 24.04
export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/snapd/desktop/applications/"

